source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-feed", "~> 0.16.0"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-theme-cayman", "~> 0.2.0"

group :jekyll_plugins do
  gem "github-pages", "~> 227", :require => false
end
